spring:
  r2dbc:
    url: r2dbc:h2:mem:///testdb
    username: sa
    password:
  sql:
    init:
      mode: always # Ensures schema and data scripts are executed
      data-locations: sql/data.sql
      schema-locations: sql/schema.sql

server:
  port: 8080
